spring.application.name=scheduler

spring.datasource.url=jdbc:postgresql://localhost:5433/scheduler
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=scheduler
spring.datasource.password=scheduler

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
admin.password=${ADMIN_PASSWORD}

server.address=0.0.0.0

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
